<#
.SYNOPSIS
    CampusCore ERP - One-Click Startup Script
    Starts Backend (Spring Boot), Cloudflare Tunnel, and Frontend (Vite).

.DESCRIPTION
    1. Launches the Spring Boot backend on port 9090
    2. Creates a Cloudflare quick-tunnel to localhost:9090
    3. Extracts the public tunnel URL and writes it to FSAD_PROJECT/.env
    4. Launches the Vite frontend dev server (reads the updated .env)

.NOTES
    Prerequisites:
      - Java 17+ and Maven on PATH (or edit $MavenBin below)
      - Node.js / npm on PATH
      - cloudflared installed and on PATH  (winget install cloudflare.cloudflared)
    
    Press Ctrl+C to stop all servers.
#>

# -- Configuration -----------------------------------------------------------
$ProjectRoot    = $PSScriptRoot
$BackendDir     = Join-Path $ProjectRoot "backend"
$FrontendDir    = Join-Path $ProjectRoot "FSAD_PROJECT"
$EnvFile        = Join-Path $FrontendDir ".env"
$BackendPort    = 9090

# -- Helper: pretty log ------------------------------------------------------
function Log($msg, $color = "Cyan") { Write-Host "[CampusCore] " -NoNewline -ForegroundColor DarkGray; Write-Host $msg -ForegroundColor $color }

# -- 1. Start Backend --------------------------------------------------------
Log "Starting Spring Boot backend on port $BackendPort ..." "Yellow"
$backendProcess = Start-Process -FilePath "$env:USERPROFILE\.maven\maven-3.9.14\bin\mvn.cmd" `
    -ArgumentList "spring-boot:run", "-q" `
    -WorkingDirectory $BackendDir `
    -PassThru `
    -WindowStyle Normal

Log "Backend PID: $($backendProcess.Id)" "Green"

# Wait for backend to become ready (poll /api/courses endpoint)
Log "Waiting for backend to be ready ..." "Yellow"
$ready = $false
for ($i = 0; $i -lt 60; $i++) {
    Start-Sleep -Seconds 3
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:$BackendPort/api/courses" -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
        if ($response.StatusCode -lt 500) { $ready = $true; break }
    } catch {
        # still starting up
        Write-Host "." -NoNewline -ForegroundColor DarkGray
    }
}
Write-Host ""
if ($ready) {
    Log "Backend is UP and running!" "Green"
} else {
    Log "WARNING: Backend may not be ready yet (timed out after 180s). Proceeding anyway..." "Red"
}

# -- 2. Start Cloudflare Tunnel ----------------------------------------------
Log "Starting Cloudflare tunnel to localhost:$BackendPort ..." "Yellow"

# We pipe cloudflared output to a temp log file so we can extract the URL
$tunnelLog = Join-Path $ProjectRoot ".cloudflared-tunnel.log"
if (Test-Path $tunnelLog) { Remove-Item $tunnelLog -Force }

$tunnelProcess = Start-Process -FilePath "cloudflared" `
    -ArgumentList "tunnel", "--url", "http://localhost:$BackendPort" `
    -RedirectStandardError $tunnelLog `
    -PassThru `
    -WindowStyle Hidden

Log "Cloudflare tunnel PID: $($tunnelProcess.Id)" "Green"

# Wait and extract the public URL from cloudflared logs
Log "Waiting for Cloudflare tunnel URL ..." "Yellow"
$tunnelUrl = $null
for ($i = 0; $i -lt 30; $i++) {
    Start-Sleep -Seconds 2
    if (Test-Path $tunnelLog) {
        $logContent = Get-Content $tunnelLog -Raw -ErrorAction SilentlyContinue
        # cloudflared logs the URL like: https://xxxx-xxxx.trycloudflare.com
        if ($logContent -match "(https://[a-zA-Z0-9\-]+\.trycloudflare\.com)") {
            $tunnelUrl = $Matches[1]
            break
        }
    }
    Write-Host "." -NoNewline -ForegroundColor DarkGray
}
Write-Host ""

if (-not $tunnelUrl) {
    Log "ERROR: Could not extract Cloudflare tunnel URL. Check $tunnelLog" "Red"
    Log "Falling back to localhost:$BackendPort" "Yellow"
    $tunnelUrl = "http://localhost:$BackendPort"
}

$apiUrl = "$tunnelUrl/api"
Log "Cloudflare Tunnel URL : $tunnelUrl" "Magenta"
Log "API Base URL          : $apiUrl" "Magenta"

# -- 3. Update .env ----------------------------------------------------------
Log "Updating $EnvFile with tunnel URL ..." "Yellow"

$envContent = "# Backend API URL - auto-generated by start-all.ps1`n# Cloudflare tunnel URL (public, no port-forwarding needed)`nVITE_API_URL=$apiUrl"

Set-Content -Path $EnvFile -Value $envContent -Encoding UTF8
Log "env updated successfully!" "Green"
Log "  VITE_API_URL=$apiUrl" "White"

# -- 4. Start Frontend -------------------------------------------------------
Log "Starting Vite frontend dev server ..." "Yellow"
$frontendProcess = Start-Process -FilePath "npm" `
    -ArgumentList "run", "dev" `
    -WorkingDirectory $FrontendDir `
    -PassThru `
    -WindowStyle Normal

Log "Frontend PID: $($frontendProcess.Id)" "Green"

# -- 5. Summary --------------------------------------------------------------
Write-Host ""
Write-Host "+------------------------------------------------------------------+" -ForegroundColor Cyan
Write-Host "|              CampusCore ERP - All Services Running               |" -ForegroundColor Cyan
Write-Host "+------------------------------------------------------------------+" -ForegroundColor Cyan
Write-Host "|                                                                  |" -ForegroundColor Cyan
Write-Host "|  Backend  (Spring Boot) : http://localhost:$BackendPort                  |" -ForegroundColor Cyan
Write-Host "|  Frontend (Vite)        : http://localhost:5173                  |" -ForegroundColor Cyan
Write-Host "|  Tunnel   (Cloudflare)  : $($tunnelUrl.PadRight(37))|" -ForegroundColor Cyan
Write-Host "|  API URL  (.env)        : $($apiUrl.PadRight(37))|" -ForegroundColor Cyan
Write-Host "|                                                                  |" -ForegroundColor Cyan
Write-Host "|  Press Ctrl+C in this window to stop all services                |" -ForegroundColor Cyan
Write-Host "+------------------------------------------------------------------+" -ForegroundColor Cyan
Write-Host ""

# -- 6. Keep alive + cleanup on Ctrl+C ---------------------------------------
try {
    Log "All services running. Press Ctrl+C to stop everything." "Green"
    while ($true) { Start-Sleep -Seconds 5 }
}
finally {
    Log "Shutting down all services ..." "Red"
    
    # Kill processes gracefully
    @($backendProcess, $tunnelProcess, $frontendProcess) | ForEach-Object {
        if ($_ -and -not $_.HasExited) {
            try { Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue } catch {}
        }
    }
    
    # Reset .env back to localhost for local dev
    $localEnv = "# Backend API URL - updated automatically by start-all.ps1`nVITE_API_URL=http://localhost:$BackendPort/api"
    Set-Content -Path $EnvFile -Value $localEnv -Encoding UTF8
    Log "env reset to localhost for next local-only dev session" "Yellow"
    
    # Clean up tunnel log
    if (Test-Path $tunnelLog) { Remove-Item $tunnelLog -Force -ErrorAction SilentlyContinue }
    
    Log "All services stopped. Goodbye!" "Green"
}
